server:
  forward-headers-strategy: native
  port: 8081
spring:
  application:
    name: main-server
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  boot:
    admin:
      context-path: /admin-ui
      ui:
        public-url: /admin-ui/
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      instance:
        preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always